# Generated by Django 3.2.9 on 2021-12-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('single', 'SINGLE OCCUPANCY'), ('share', 'DOUBLE OCCUPANCY')], default='choose', max_length=50)),
                ('vacant', models.BooleanField(default=False)),
                ('rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('room', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.room')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('enrollment', models.CharField(blank=True, max_length=10, unique=True)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=250)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.room')),
            ],
        ),
    ]
